import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App";
import "@fontsource/manrope/latin-ext-400.css";
import "@fontsource/manrope/latin-ext-500.css";
import "@fontsource/manrope/latin-ext-600.css";
import "@fontsource/manrope/latin-400.css";
import "@fontsource/manrope/latin-500.css";
import "@fontsource/manrope/latin-600.css";
import "@fontsource/manrope/latin-ext-800.css";
import "@fontsource/manrope/latin-800.css";
import "./styles.css";
import "./scroll/scroll.css";
const root = document.getElementById("root")!;
if (root.querySelector("main")) hydrateRoot(root, <App />);
else createRoot(root).render(<App />);
